Some minor error fixes.
HERA-Team/hera_corr_f pull request #73
Opened 2021-12-15 23:54 UTC by david-deboer

This fixed the handful of small errors I found in looking through the code.  I had also done a few tweaks in the new methods.

2021-12-15 23:57 UTC, david-deboer commented
My editor must also automatically remove the trailing spaces...

2021-12-16 00:18 UTC, AaronParsons requested changes
Two minor suggestions to a couple of edits. Otherwise looks great. good catches.

2021-12-16 00:18 UTC, AaronParsons commented on control_software/src/blocks.py
> +        print("THIS DOESN'T DO ANYTHING")
Put a "pass" here instead of printing.

2021-12-16 00:18 UTC, AaronParsons commented on control_software/src/hera_corr.py
> +                               (host, ','.join(['(%d%s)' % (ant,pol)
The first %d looks like it should have been *stream*. Can you put it back and set it to stream?

2021-12-17 15:03 UTC, AaronParsons approved these changes
All in order. Next time, can we separate code cleanup from new functionality?

2021-12-17 15:03 UTC, merged